version: '3'

services:
  bfox.dev:
    container_name: bfox.dev
    restart: unless-stopped
    build: .

  caddy:
    image: caddy/caddy:2.4.3-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
      - ./site:/srv
# version: '3'

# services:
#   app:
#     image: docker-nextjs-dev
#     build: .
#     ports:
#       - 3000:3000
