version: '2'
services:
  node:
    image: 'node:8'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - '8081'
    command: 'npm start'

  bfox.dev:
    container_name: bfox.dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile

  caddy:
    image: caddy/caddy:2.4.3-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
      - ./site:/srv
