import { NextPage } from "next"
import Head from "next/head"
import styles from '../styles/Home.module.css'

const Ben: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h2>
        <a href='/resume.pdf'  download>Download more formal</a>
      </h2>
      <main className={styles.main}>
        <h1>
          Ben Fox
        </h1>
        <p>
          I am Ben
        </p>
        <section>
          <h2>
            Experience
          </h2>
          <div>
            <h3>
              Software Engineer
            </h3>
            <p>
              <a href="https://www.thescore.com">
                The Score
              </a>
            </p>
            <p>
              <em>
                2020 - Present
              </em>
            </p>
          </div>
        </section>
        <section>
          <h2>
            Education
          </h2>
          <div>
            <h3>
              Bachelor of Science in Computer Science
            </h3>
            <p>
              <a href="https://www.ualberta.ca">
                University of Alberta
              </a>
            </p>
            <p>
              <em>
                2016 - 2020
              </em>
            </p>
          </div>
        </section>
        <section>
          <h2>
            Skills
          </h2>
          <div>
            <h3>
              Languages
            </h3>
            <ul>
              <li>
                JavaScript
              </li>
              <li>
                TypeScript
              </li>
            </ul>
          </div>
          <div>
            <h3>
              Frameworks
            </h3>
            <ul>
              <li>
                React
              </li>
              <li>
                Next.js
              </li>
              <li>
                Express
              </li>
            </ul>
          </div>
          <div>
            <h3>
              Databases
            </h3>
            <ul>
              <li>
                PostgreSQL
              </li>
              <li>
                MongoDB
              </li>
            </ul>
          </div>
          <div>
            <h3>
              Tools
            </h3>
            <ul>
              <li>
                Git
              </li>
              <li>
                Docker
              </li>
              <li>
                AWS
              </li>
            </ul>
          </div>
        </section>
        <section>
          <h2>
            Other
          </h2>
          <div>
            <h3>
              Interests
            </h3>
            <ul>
              <li>
                <a href="https://www.youtube.com/watch?v=QH2-TGUlwu4">
                  Music
                </a>
              </li>
              <li>
                <a href="https://www.youtube.com/watch?v=QH2-TGUlwu4">
                  Video Games
                </a>
              </li>
              <li>
                <a href="https://www.youtube.com/watch?v=QH2-TGUlwu4">
                  Sports
                </a>
              </li>
            </ul>
          </div>
        </section>
      </main>

  </>
  )
}

export default Ben