import { NextPage } from "next"
import Head from "next/head"
import styles from '../styles/Resume.module.css'

const Ben: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.resume}>
        <h2>
          <a href='/resume.pdf' download>Download more formal</a>
        </h2>
        <h1>
          Ben Fox
        </h1>
        <p>
          I am Ben
        </p>
        <section className={styles.resumeSection}>
          <h2 className={styles.resumeHeading}>
            Experience
          </h2>
          <div className={styles.resumeEntry}>
            <p className={styles.date}>
              <em>
                2017 - 2022
              </em>
            </p>
            <h3 className={styles.resumePosition} >
              Business Teacher
            </h3>
            <p>
              <a href="https://www.thescore.com">
                Herndon High School
              </a>
            </p>
            <p>
              <a href="https://www.thescore.com">
                Department Lead for Digital Applications, a class teaching English Language learners common tech use in FCPS. Spearheaded Special Education first Special Education course at Herndon High school.Chair of the 'We Are Herndon' committee to integrate community into the school culture. Sponsored a team of students selected by Carnegie Melon Computer Science 'Fall Showcase' for coding in Python. Lead Mentor to students from nontraditional backgrounds, to facilitate setting academic, social, and personal goals. Junior Varsity Basketball coach and school representative liaison for student athletes.
              </a>
            </p>
          </div>
        </section>
        <section className={styles.resumeSection}>
          <h2 className={styles.resumeHeading}>
            Education
          </h2>
          <div>
            <div className={styles.resumeEntry}>
              <p className={styles.date}>
                <em>
                  2012 - 2016
                </em>
              </p>
              <h3 className={styles.resumePosition} >
                Master of Education
              </h3>
              <p>
                <a href="https://www.ualberta.ca">
                  Virginia Tech
                </a>
              </p>
            </div>
            <div className={styles.resumeEntry}>
              <p className={styles.date}>
                <em>
                  2016 - 2017
                </em>
              </p>
              <h3 className={styles.resumePosition} >
                Bachelor of Science in Business Information Technology
              </h3>
              <p>
                <a href="https://www.ualberta.ca">
                  Virginia Tech
                </a>
              </p>
            </div>
          </div>
        </section>
        <section className={styles.resumeSection}>
          <h2 className={styles.resumeHeading}>
            Skills
          </h2>
          <div>
            <h3>
              Languages
            </h3>
            <ul>
              <li>
                TypeScript
              </li>
              <li>
                JavaScript
              </li>
              <li>
                HTML
              </li>
              <li>
                CSS
              </li>
            </ul>
          </div>
          <div>
            <h3>
              Frameworks
            </h3>
            <ul>
              <li>
                React
              </li>
              <li>
                Next.js
              </li>
              <li>
                Express
              </li>
              <li>
                Node
              </li>
              <li>
                SASS
              </li>
            </ul>
          </div>
          <div>
            <h3>
              Databases
            </h3>
            <ul>
              <li>
                PostgreSQL
              </li>
              <li>
                MongoDB
              </li>
            </ul>
          </div>
          <div>
            <h3>
              Tools
            </h3>
            <ul>
              <li>
                Git
              </li>
              <li>
                Docker
              </li>
              <li>
                Heroku
              </li>
              <li>
                VS Code
              </li>
            </ul>
          </div>
        </section>
        <section className={styles.resumeSection}>
          <h2 className={styles.resumeHeading}>
            Other
          </h2>
          <div>
            <div className={styles.resumeEntry}>
              <p className={styles.date}>
                <em>
                  2020 - 2022
                </em>
              </p>
              <h3 className={styles.resumePosition} >
                Trapeze Artist
              </h3>
              <p>
                <a href="https://www.thescore.com">
                  Trapeze School New York, DC
                </a>
              </p>
              <p>
                responsibilities include
              </p>
            </div>
            <div className={styles.resumeEntry}>
              <p className={styles.date}>
                <em>
                  2020 - Present
                </em>
              </p>

              <h3 className={styles.resumePosition} >
                Basketball Coach
              </h3>
              <p>
                <a href="https://www.thescore.com">
                  The Score
                </a>
              </p>
              <p>
                responsibilities include
              </p>

            </div>
          </div>
        </section>
      </main>

    </>
  )
}

export default Ben