import type { NextPage } from 'next'
import Hero from '../Components/Hero'
import Head from 'next/head'
import Projects from '../Components/Projects'
import Skills from '../Components/Skills'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.bigHeader}>
          Bfox.dev
        </h1>
        <Hero />
        <h2 className={styles.bigHeader}>Projects</h2>
        <Projects />
        <h2 className={styles.bigHeader}>Skills</h2>
        <Skills />
      </main>

  </>
  )
}

export default Home
